import Link from "next/link";
import type { ReactNode } from "react";

import AiMusicIntroCta from "@/components/ai-music/AiMusicIntroCta";
import ArticleFaqList from "@/components/articles/ArticleFaqList";
import { articleBodyStackClass } from "@/components/articles/typography";
import {
  KAK_VYLOZHIT_II_MUZYKU_BREADCRUMB_TITLE,
  KAK_VYLOZHIT_II_MUZYKU_FAQ,
  KAK_VYLOZHIT_II_MUZYKU_PAGE_H1,
} from "@/lib/seo/kak-vylozhit-ii-muzyku";

const heading = "scroll-mt-24 text-2xl font-semibold tracking-tight text-[#25135c] sm:text-3xl";
const section = "mt-14 max-w-3xl sm:mt-20";
const visual = "mt-8 overflow-hidden rounded-[24px] border border-[#d8c8ee] bg-gradient-to-br from-[#fffaff] to-[#efe4fb] p-5 text-[#4a3d73] shadow-[0_12px_30px_rgba(90,60,145,0.08)] sm:p-7";
const linkClass = "font-medium text-[#7042c5] underline decoration-[#c9b6ea] underline-offset-4 hover:text-[#56318f]";
const card = "rounded-2xl border border-white/80 bg-white/85 px-3 py-3 text-center text-sm font-medium shadow-sm";

function Visual({ number, children, caption }: { number: string; children: ReactNode; caption: string }) {
  return <figure className={visual} data-visual-block={number}>{children}<figcaption className="mt-5 text-sm leading-6 text-[#6f6291]">{caption}</figcaption></figure>;
}

function PublicationFlowVisual() {
  const steps = ["Готовый трек", "Проверка прав", "Аудиофайл", "Название", "Обложка", "Публикация"];
  return <Visual number="1" caption="Перед публикацией ИИ-музыки стоит пройти путь от проверки прав до подготовки самого релиза."><div className="grid gap-2 text-center text-sm font-semibold sm:grid-cols-[repeat(6,minmax(0,1fr))]">{steps.map((step, index) => <div className="contents" key={step}><div className={index === 5 ? "rounded-2xl bg-[#7042c5] px-3 py-3 text-white shadow-sm" : card}>{step}</div>{index < 5 && <div className="py-0.5 text-xl text-[#7042c5] sm:hidden">↓</div>}</div>)}</div></Visual>;
}

function ReleaseKitVisual() {
  return <Visual number="2" caption="Для публикации нужен не один аудиофайл – заранее соберите основные материалы релиза."><div className="grid gap-3 sm:grid-cols-[1.7fr_auto_1fr] sm:items-center"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{["WAV/MP3", "Название", "Имя автора", "Обложка", "Описание", "Метаданные/права"].map((item) => <div className={card} key={item}>{item}</div>)}</div><div className="text-center text-xl text-[#7042c5]">→</div><div className="rounded-3xl bg-[#7042c5] p-6 text-center font-semibold text-white">Готово<br />к публикации</div></div></Visual>;
}

function ChannelsVisual() {
  return <Visual number="3" caption="Один трек можно публиковать разными способами – выбор зависит от цели автора."><div className="grid gap-4 text-center sm:grid-cols-[1fr_auto_2fr] sm:items-center"><div className="rounded-3xl bg-[#7042c5] px-4 py-6 font-semibold text-white">Готовая<br />композиция</div><div className="text-xl text-[#7042c5]">→</div><div className="grid gap-2 sm:grid-cols-3"><div className={card}>Дистрибьютор<br /><span className="text-xs font-normal">Яндекс Музыка / Spotify / YouTube Music</span></div><div className={card}>YouTube<br /><span className="text-xs font-normal">Собственный канал</span></div><div className={card}>АудиоЛад<br /><span className="text-xs font-normal">Страница музыкального продукта</span></div></div></div></Visual>;
}

function FormatsVisual() {
  return <Visual number="4" caption="Один аудиофайл может стать частью разных форматов и каналов публикации."><div className="grid gap-4 text-center sm:grid-cols-[1fr_auto_1.5fr] sm:items-center"><div className="rounded-2xl border border-[#c9b6ea] bg-white px-4 py-5 font-semibold">Спокойная музыка<br />для массажа</div><div className="text-xl text-[#7042c5]">→</div><div className="grid grid-cols-3 gap-2"><div className={card}>Стриминг</div><div className={card}>YouTube-видео</div><div className={card}>Страница музыкального продукта</div><div className={`${card} col-span-3`}>Несколько треков → Альбом / плейлист / музыкальная программа</div></div></div></Visual>;
}

export default function KakVylozhitIiMuzykuPageView() {
  return <article className="pb-16 pt-4">
    <nav aria-label="Хлебные крошки" className="text-sm text-[#7d70a2]"><ol className="flex flex-wrap gap-1.5"><li><Link href="/" className={linkClass}>Главная</Link></li><li>/</li><li><Link href="/for-authors" className={linkClass}>Авторам</Link></li><li>/</li><li aria-current="page">{KAK_VYLOZHIT_II_MUZYKU_BREADCRUMB_TITLE}</li></ol></nav>
    <header className="mt-8 max-w-3xl sm:mt-10"><h1 className="text-[1.85rem] font-semibold leading-tight tracking-tight text-[#25135c] sm:text-4xl">{KAK_VYLOZHIT_II_MUZYKU_PAGE_H1}</h1><div className={`mt-7 ${articleBodyStackClass}`}><p>Если музыка уже создана, следующий шаг – подготовить её к публикации и выбрать подходящий канал. Не обязательно начинать с альбома: можно выпустить один готовый трек.</p><p>Если композиции ещё нет, сначала прочитайте <Link href="/kak-sozdat-ii-muzyku" className={linkClass}>Как создать ИИ-музыку с помощью нейросети: пошаговая инструкция</Link>.</p><p>Ниже – практический чек-лист: от проверки прав и материалов релиза до публикации на стримингах, YouTube или напрямую.</p></div></header>
    <PublicationFlowVisual />
    <section className={section} id="korotko"><h2 className={heading}>Коротко</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Перед публикацией проверьте права на трек, подготовьте аудиофайл, название, обложку и описание. Затем выберите задачу: стриминги через дистрибьютора, ролик на YouTube или самостоятельный музыкальный продукт.</p><p>Один и тот же трек может участвовать в нескольких сценариях, если это разрешают ваши права и правила площадок.</p></div></section>
    <section className={section} id="shag-1"><h2 className={heading}>Шаг 1. Проверьте права на музыку</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>До загрузки убедитесь, что условия сервиса, где создана композиция, позволяют выбранное использование. Отдельно проверьте вокал, семплы, чужие тексты и похожесть на конкретных исполнителей.</p><p>Для музыки из Suno права на использование зависят от актуальных условий и плана. Перед коммерческой публикацией сверяйтесь с <a href="https://suno.com/terms-of-service" className={linkClass} target="_blank" rel="noopener noreferrer">условиями Suno</a> и правилами площадки назначения.</p><p>Не выдавайте себя за другого артиста и не публикуйте материал, на который у вас нет прав.</p></div></section>
    <section className={section} id="shag-2"><h2 className={heading}>Шаг 2. Подготовьте комплект релиза</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Для публикации нужен не только файл. Сохраните финальную версию трека в требуемом формате, подготовьте название, имя автора, обложку, описание и сведения о правах.</p><p>Название и описание должны помогать слушателю понять назначение музыки. Например, «Спокойная музыка для массажа» сразу объясняет контекст лучше, чем случайное рабочее имя файла.</p></div><ReleaseKitVisual /></section>
    <section className={section} id="shag-3"><h2 className={heading}>Шаг 3. Выберите, куда загрузить музыку</h2><div className={`mt-5 ${articleBodyStackClass}`}><h3 className="text-xl font-semibold text-[#25135c]">Стриминги через дистрибьютора</h3><p>Для публичных релизов в музыкальных каталогах обычно нужен дистрибьютор или лейбл. Spotify прямо указывает этот путь в <a href="https://artists.spotify.com/get-started" className={linkClass} target="_blank" rel="noopener noreferrer">руководстве для артистов</a>. Подробнее о модели распространения – в статье <Link href="/distribyutor-ii-muzyki" className={linkClass}>Дистрибьютор ИИ-музыки: где публиковать и продавать нейромузыку</Link>.</p><h3 className="text-xl font-semibold text-[#25135c]">YouTube</h3><p>На собственном канале можно опубликовать видео с музыкой. Это не то же самое, что официальный релиз в YouTube Music: его доставляют через агрегатора согласно <a href="https://support.google.com/youtubemusic/answer/9105565" className={linkClass} target="_blank" rel="noopener noreferrer">справке YouTube Music</a>.</p><h3 className="text-xl font-semibold text-[#25135c]">Прямой музыкальный продукт</h3><p>Музыку можно оформить как отдельный продукт с собственной страницей, обложкой и описанием. В этом сценарии АудиоЛад не выступает музыкальным дистрибьютором.</p></div><ChannelsVisual /></section>
    <section className={section} id="yandex-youtube"><h2 className={heading}>Важно: личная загрузка и публичный релиз – не одно и то же</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Фраза «загрузить в Яндекс Музыку» имеет два значения. <a href="https://yandex.ru/support/music/ru/collection/uploading_own_tracks" className={linkClass} target="_blank" rel="noopener noreferrer">Загрузка своих треков в личную фонотеку</a> нужна для личного прослушивания. Для публичного релиза исполнители и правообладатели работают через партнёров, как описано в <a href="https://yandex.ru/support/music/ru/performers-and-copyright-holders/terms" className={linkClass} target="_blank" rel="noopener noreferrer">условиях Яндекс Музыки</a>.</p><p>Так же и в YouTube Music: <a href="https://support.google.com/youtubemusic/answer/9716522" className={linkClass} target="_blank" rel="noopener noreferrer">личные загрузки</a> доступны для воспроизведения только загрузившему их пользователю, а не становятся публичным каталоговым релизом.</p></div></section>
    <section className={section} id="shag-4"><h2 className={heading}>Шаг 4. Решите, публикуете один трек или несколько</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Один трек можно выпустить без альбома: как сингл, видео или самостоятельный продукт. Когда появится несколько связанных композиций, объедините их в альбом, плейлист или музыкальную программу.</p><p>Не придумывайте срок выпуска заранее: требования и проверка материалов зависят от выбранного канала.</p></div></section>
    <section className={section} id="shag-5"><h2 className={heading}>Шаг 5. Отличите трек от музыкального продукта</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Трек – это аудиофайл. Музыкальный продукт – понятное предложение для слушателя: с названием, обложкой, описанием и сценарием использования.</p><p>Один файл «Спокойная музыка для массажа» может стать стриминговым синглом, YouTube-видео или страницей музыкального продукта. Несколько треков можно собрать в более длинный формат.</p></div><FormatsVisual /></section>
    <section className={section} id="shag-6"><h2 className={heading}>Шаг 6. Назначьте дату и пройдите проверку перед выпуском</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Перед отправкой ещё раз прослушайте финальный файл, проверьте название и автора, читаемость обложки, описание и выбранные площадки. Сохраните исходные материалы и подтверждения прав.</p><p>Если дистрибьютор или площадка запрашивает дополнительные сведения, отвечайте на них до публикации, а не после неё.</p></div></section>
    <section className={section} id="shag-7"><h2 className={heading}>Шаг 7. Собирайте каталог, а не случайные загрузки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>После первой публикации продолжайте развивать понятные тематические серии. Так отдельные треки со временем превращаются в каталог, в котором слушателю легче находить нужную музыку.</p></div></section>
    <AiMusicIntroCta paragraphs={["Даже если вы пока только готовитесь к первой публикации, загляните в АудиоЛад. Послушайте музыку и аудиопрактики, посмотрите, как оформлены продукты и какие возможности есть у авторов.", "Можно зарегистрироваться бесплатно, познакомиться с площадкой как слушатель и автор и вернуться к публикации своей музыки тогда, когда будете готовы."]} />
    <section className={section} id="neskolko-ploshchadok"><h2 className={heading}>Можно ли разместить одну музыку сразу на нескольких площадках</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Да, один трек может быть доступен на стримингах, в видео на YouTube и как отдельный продукт. Перед этим убедитесь, что условия генератора, дистрибьютора и каждой площадки не ограничивают ваш сценарий.</p><p>Не создавайте противоречивые метаданные: имя автора, название и обложка должны быть согласованы там, где это возможно.</p></div></section>
    <section className={section} id="ai-disclosure"><h2 className={heading}>Нужно ли сообщать, что музыка создана ИИ</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Сверяйте требования выбранного сервиса перед загрузкой. Например, DistroKid принимает музыку, созданную AI-инструментами, при наличии прав, запрете на имитацию других артистов, нарушение прав и массовый спам; при необходимости его поток загрузки просит указать AI credits. Изучите <a href="https://support.distrokid.com/hc/en-us/articles/41182362733715-Can-I-Upload-Music-Made-With-AI-Tools-to-DistroKid" className={linkClass} target="_blank" rel="noopener noreferrer">актуальную политику DistroKid об AI-музыке</a>.</p></div></section>
    <section className={section} id="gde-nachat"><h2 className={heading}>Где публиковать сначала</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Начните с канала, который соответствует цели: дистрибьютор – для публичного стримингового релиза, YouTube – для видео и аудитории канала, прямая страница продукта – для самостоятельного предложения слушателю.</p><p>Если ваша цель – коммерческая работа с музыкой на платформе, посмотрите <Link href="/kak-zarabatyvat-na-ii-muzyke-v-audiolad" className={linkClass}>Как зарабатывать на своей ИИ-музыке в АудиоЛаде</Link>.</p></div></section>
    <section className={section} id="faq"><h2 className={heading}>Частые вопросы</h2><ArticleFaqList items={KAK_VYLOZHIT_II_MUZYKU_FAQ} /></section>
  </article>;
}
