import Link from "next/link";
import type { ReactNode } from "react";

import AiMusicIntroCta from "@/components/ai-music/AiMusicIntroCta";
import ArticleFaqList from "@/components/articles/ArticleFaqList";
import { articleBodyStackClass } from "@/components/articles/typography";
import {
  KAK_VYLOZHIT_II_MUZYKU_BREADCRUMB_TITLE,
  KAK_VYLOZHIT_II_MUZYKU_FAQ,
  KAK_VYLOZHIT_II_MUZYKU_PAGE_H1,
} from "@/lib/seo/kak-vylozhit-ii-muzyku";

const heading = "scroll-mt-24 text-2xl font-semibold tracking-tight text-[#25135c] sm:text-3xl";
const section = "mt-14 max-w-3xl sm:mt-20";
const visual = "mt-8 overflow-hidden rounded-[24px] border border-[#d8c8ee] bg-gradient-to-br from-[#fffaff] to-[#efe4fb] p-5 text-[#4a3d73] shadow-[0_12px_30px_rgba(90,60,145,0.08)] sm:p-7";
const linkClass = "font-medium text-[#7042c5] underline decoration-[#c9b6ea] underline-offset-4 hover:text-[#56318f]";
const card = "rounded-2xl border border-white/80 bg-white/85 px-3 py-3 text-center text-sm font-medium shadow-sm";

function Visual({ number, children, caption }: { number: string; children: ReactNode; caption: string }) {
  return <figure className={visual} data-visual-block={number}>{children}<figcaption className="mt-5 text-sm leading-6 text-[#6f6291]">{caption}</figcaption></figure>;
}

function PublicationFlowVisual() {
  const steps = ["Готовый трек", "Проверка прав", "Аудиофайл", "Название", "Обложка", "Публикация"];
  return <Visual number="1" caption="Перед публикацией ИИ-музыки стоит пройти путь от проверки прав до подготовки самого релиза."><div className="grid gap-2 text-center text-sm font-semibold sm:grid-cols-[repeat(6,minmax(0,1fr))]">{steps.map((step, index) => <div className="contents" key={step}><div className={index === 5 ? "rounded-2xl bg-[#7042c5] px-3 py-3 text-white shadow-sm" : card}>{step}</div>{index < 5 && <div className="py-0.5 text-xl text-[#7042c5] sm:hidden">↓</div>}</div>)}</div></Visual>;
}

function ReleaseKitVisual() {
  return <Visual number="2" caption="Для публикации нужен не один аудиофайл – заранее соберите основные материалы релиза."><div className="grid gap-3 sm:grid-cols-[1.7fr_auto_1fr] sm:items-center"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{["WAV/MP3", "Название", "Имя автора", "Обложка", "Описание", "Метаданные/права"].map((item) => <div className={card} key={item}>{item}</div>)}</div><div className="text-center text-xl text-[#7042c5]">→</div><div className="rounded-3xl bg-[#7042c5] p-6 text-center font-semibold text-white">Готово<br />к публикации</div></div></Visual>;
}

function ChannelsVisual() {
  return <Visual number="3" caption="Один трек можно публиковать разными способами – выбор зависит от цели автора."><div className="grid gap-4 text-center sm:grid-cols-[1fr_auto_2fr] sm:items-center"><div className="rounded-3xl bg-[#7042c5] px-4 py-6 font-semibold text-white">Готовая<br />композиция</div><div className="text-xl text-[#7042c5]">→</div><div className="grid gap-2 sm:grid-cols-3"><div className={card}>Дистрибьютор<br /><span className="text-xs font-normal">Яндекс Музыка / Spotify / YouTube Music</span></div><div className={card}>YouTube<br /><span className="text-xs font-normal">Собственный канал</span></div><div className={card}>АудиоЛад<br /><span className="text-xs font-normal">Страница музыкального продукта</span></div></div></div></Visual>;
}

function FormatsVisual() {
  return <Visual number="4" caption="Один аудиофайл может стать частью разных форматов и каналов публикации."><div className="grid gap-4 text-center sm:grid-cols-[1fr_auto_1.5fr] sm:items-center"><div className="rounded-2xl border border-[#c9b6ea] bg-white px-4 py-5 font-semibold">Спокойная музыка<br />для массажа</div><div className="text-xl text-[#7042c5]">→</div><div className="grid grid-cols-3 gap-2"><div className={card}>Стриминг</div><div className={card}>YouTube-видео</div><div className={card}>Страница музыкального продукта</div><div className={`${card} col-span-3`}>Несколько треков → Альбом / плейлист / музыкальная программа</div></div></div></Visual>;
}

export default function KakVylozhitIiMuzykuPageView() {
  return <article className="pb-16 pt-4">
    <nav aria-label="Хлебные крошки" className="text-sm text-[#7d70a2]"><ol className="flex flex-wrap gap-1.5"><li><Link href="/" className={linkClass}>Главная</Link></li><li>/</li><li><Link href="/for-authors" className={linkClass}>Авторам</Link></li><li>/</li><li aria-current="page">{KAK_VYLOZHIT_II_MUZYKU_BREADCRUMB_TITLE}</li></ol></nav>
    <header className="mt-8 max-w-3xl sm:mt-10"><h1 className="text-[1.85rem] font-semibold leading-tight tracking-tight text-[#25135c] sm:text-4xl">{KAK_VYLOZHIT_II_MUZYKU_PAGE_H1}</h1><div className={`mt-7 ${articleBodyStackClass}`}><p>Если музыка уже создана, следующий шаг – подготовить её к публикации и выбрать подходящий канал. Не обязательно начинать с альбома: можно выпустить один готовый трек.</p><p>Если композиции ещё нет, сначала прочитайте <Link href="/kak-sozdat-ii-muzyku" className={linkClass}>Как создать ИИ-музыку с помощью нейросети: пошаговая инструкция</Link>.</p><p>Ниже – практический чек-лист: от проверки прав и материалов релиза до публикации на стримингах, YouTube или напрямую.</p></div></header>
    <PublicationFlowVisual />
    <section className={section} id="korotko"><h2 className={heading}>Коротко</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Перед публикацией проверьте права на трек, подготовьте аудиофайл, название, обложку и описание. Затем выберите задачу: стриминги через дистрибьютора, ролик на YouTube или самостоятельный музыкальный продукт.</p><p>Один и тот же трек может участвовать в нескольких сценариях, если это разрешают ваши права и правила площадок.</p></div></section>
    <section className={section} id="shag-1"><h2 className={heading}>Шаг 1. Проверьте, можно ли публиковать созданную музыку</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Перед загрузкой нужно понять, есть ли у вас право использовать получившийся трек публично и коммерчески. Особенно это важно для музыки, созданной с помощью ИИ.</p><p>Проверьте:</p><ul><li>условия нейросети, в которой создавался трек;</li><li>тариф, на котором он был создан;</li><li>право на коммерческое использование;</li><li>происхождение использованных текстов;</li><li>использованные голоса;</li><li>семплы и исходные аудиоматериалы;</li><li>условия площадки, куда вы собираетесь загружать музыку.</li></ul><p>Сам факт того, что сервис позволил скачать MP3, ещё не означает автоматически, что композицию разрешено продавать или распространять коммерчески.</p><p>Для музыки из Suno права на использование зависят от актуальных условий и плана. Перед коммерческой публикацией сверяйтесь с <a href="https://suno.com/terms-of-service" className={linkClass} target="_blank" rel="noopener noreferrer">условиями Suno</a> и правилами площадки назначения.</p><p>Как официальный пример, DistroKid допускает ИИ-музыку при наличии необходимых прав и ограничивает нарушение чужих прав, имитацию личности или голоса и спам. Изучите <a href="https://support.distrokid.com/hc/en-us/articles/41182362733715-Can-I-Upload-Music-Made-With-AI-Tools-to-DistroKid" className={linkClass} target="_blank" rel="noopener noreferrer">политику DistroKid об AI-музыке</a> перед отправкой релиза.</p></div></section>
    <section className={section} id="shag-2"><h2 className={heading}>Шаг 2. Подготовьте трек к публикации</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Одного аудиофайла обычно недостаточно. Для нормального релиза заранее подготовьте небольшой комплект.</p><h3 className="text-xl font-semibold text-[#25135c]">Аудиофайл</h3><p>Сохраните финальную версию. Прослушайте её полностью: начало, переходы, уровень громкости, окончание, отсутствие случайных обрывов и нежелательного голоса или артефактов генерации.</p><p>Не стоит загружать первую понравившуюся генерацию только потому, что она уже существует.</p><h3 className="text-xl font-semibold text-[#25135c]">Название</h3><p>Название должно помогать понять, что слушать. Moonlight Flow можно оставить как художественное название. Если музыка создана под задачу, полезно понятное позиционирование: «Музыка для вечернего массажа» или «Спокойный джаз для работы». Особенно это важно там, где музыку находят через поиск.</p><h3 className="text-xl font-semibold text-[#25135c]">Обложка</h3><p>Подготовьте квадратное изображение хорошего качества. Не перегружайте его мелким текстом: на маленьком экране обложка должна оставаться понятной даже как небольшая карточка.</p><h3 className="text-xl font-semibold text-[#25135c]">Имя автора</h3><p>Заранее определите имя: настоящее, псевдоним или название проекта. Лучше не менять его от трека к треку без необходимости – под одним именем собирается каталог.</p><h3 className="text-xl font-semibold text-[#25135c]">Описание и назначение</h3><p>Не на каждой стриминговой площадке длинное описание критично, но для собственной страницы продукта оно очень полезно. Ответьте на простой вопрос: <b>что это за музыка и когда её слушать?</b></p></div><ReleaseKitVisual /></section>
    <section className={section} id="shag-3"><h2 className={heading}>Шаг 3. Выберите, куда вы хотите загрузить музыку</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Условно есть три основных маршрута.</p><h3 className="text-xl font-semibold text-[#25135c]">1. Стриминговые сервисы</h3><p>Если композиция должна появиться в обычном музыкальном каталоге рядом с другими артистами, это дистрибуция. Один дистрибьютор может передавать релиз сразу на несколько сервисов: Яндекс Музыка, Spotify, YouTube Music и другие.</p><p>Для публичного релиза Яндекс Музыка направляет исполнителей и правообладателей к партнёрам – сверяйтесь с <a href="https://yandex.ru/support/music/ru/performers-and-copyright-holders/terms" className={linkClass} target="_blank" rel="noopener noreferrer">актуальными условиями для исполнителей и правообладателей</a>. Spotify также указывает путь через дистрибьютора или лейбл в <a href="https://artists.spotify.com/get-started" className={linkClass} target="_blank" rel="noopener noreferrer">руководстве для артистов</a>.</p><p>Подробнее: <Link href="/distribyutor-ii-muzyki" className={linkClass}>Дистрибьютор ИИ-музыки: где публиковать и продавать нейромузыку</Link>.</p><h3 className="text-xl font-semibold text-[#25135c]">2. YouTube</h3><p>Можно представить музыку на собственном YouTube-канале: как видео со статичной обложкой, визуализатором или видеорядом. Но обычная публикация видео на YouTube и попадание релиза в музыкальный каталог YouTube Music – разные вещи. Для официальной доставки в каталог используется агрегатор, как объясняет <a href="https://support.google.com/youtubemusic/answer/9105565" className={linkClass} target="_blank" rel="noopener noreferrer">справка YouTube Music</a>.</p><h3 className="text-xl font-semibold text-[#25135c]">3. Прямая публикация музыкального продукта</h3><p>Другой подход – создать отдельную страницу композиции, где можно показать название, автора, обложку, описание, саму музыку, назначение и другие работы автора.</p><p>В АудиоЛаде музыка может существовать как самостоятельный аудиопродукт – это другой сценарий, чем обычный стриминг, а не классическая музыкальная дистрибуция.</p></div><ChannelsVisual /></section>
    <section className={section} id="yandex-youtube"><h2 className={heading}>Важно: «загрузить в Яндекс Музыку» может означать две разные вещи</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>В Яндекс Музыке есть <a href="https://yandex.ru/support/music/ru/collection/uploading_own_tracks" className={linkClass} target="_blank" rel="noopener noreferrer">загрузка собственного аудиофайла для личного прослушивания</a>. Это личная библиотека, а не публичный релиз для всех слушателей.</p><p>Для официальной публикации артиста действует актуальный механизм Яндекса через партнёров, описанный в <a href="https://yandex.ru/support/music/ru/performers-and-copyright-holders/terms" className={linkClass} target="_blank" rel="noopener noreferrer">условиях для исполнителей и правообладателей</a>.</p><p>Аналогично в YouTube Music: <a href="https://support.google.com/youtubemusic/answer/9716522" className={linkClass} target="_blank" rel="noopener noreferrer">личная загрузка в библиотеку</a> доступна для воспроизведения только загрузившему её пользователю, тогда как публичный музыкальный релиз доставляется через дистрибьютора.</p><p className="font-semibold text-[#25135c]">Ключевой вопрос: это публикация для слушателей или просто добавление файла в мою личную библиотеку?</p></div></section>
    <section className={section} id="shag-4"><h2 className={heading}>Шаг 4. Решите, публикуете один трек или несколько</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Один трек можно выпустить без альбома: как сингл, видео или самостоятельный продукт. Когда появится несколько связанных композиций, объедините их в альбом, плейлист или музыкальную программу.</p><p>Не придумывайте срок выпуска заранее: требования и проверка материалов зависят от выбранного канала.</p></div></section>
    <section className={section} id="shag-5"><h2 className={heading}>Шаг 5. Отличите трек от музыкального продукта</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Трек – это аудиофайл. Музыкальный продукт – понятное предложение для слушателя: с названием, обложкой, описанием и сценарием использования.</p><p>Один файл «Спокойная музыка для массажа» может стать стриминговым синглом, YouTube-видео или страницей музыкального продукта. Несколько треков можно собрать в более длинный формат.</p></div><FormatsVisual /></section>
    <section className={section} id="shag-6"><h2 className={heading}>Шаг 6. Назначьте дату и пройдите проверку перед выпуском</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Перед отправкой ещё раз прослушайте финальный файл, проверьте название и автора, читаемость обложки, описание и выбранные площадки. Сохраните исходные материалы и подтверждения прав.</p><p>Если дистрибьютор или площадка запрашивает дополнительные сведения, отвечайте на них до публикации, а не после неё.</p></div></section>
    <section className={section} id="shag-7"><h2 className={heading}>Шаг 7. Собирайте каталог, а не случайные загрузки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>После первой публикации продолжайте развивать понятные тематические серии. Так отдельные треки со временем превращаются в каталог, в котором слушателю легче находить нужную музыку.</p></div></section>
    <AiMusicIntroCta paragraphs={["Даже если вы пока только готовитесь к первой публикации, загляните в АудиоЛад. Послушайте музыку и аудиопрактики, посмотрите, как оформлены продукты и какие возможности есть у авторов.", "Можно зарегистрироваться бесплатно, познакомиться с площадкой как слушатель и автор и вернуться к публикации своей музыки тогда, когда будете готовы."]} />
    <section className={section} id="neskolko-ploshchadok"><h2 className={heading}>Можно ли разместить одну музыку сразу на нескольких площадках</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Да, один трек может быть доступен на стримингах, в видео на YouTube и как отдельный продукт. Перед этим убедитесь, что условия генератора, дистрибьютора и каждой площадки не ограничивают ваш сценарий.</p><p>Не создавайте противоречивые метаданные: имя автора, название и обложка должны быть согласованы там, где это возможно.</p></div></section>
    <section className={section} id="ai-disclosure"><h2 className={heading}>Нужно ли сообщать, что музыка создана ИИ</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Сверяйте требования выбранного сервиса перед загрузкой. Например, DistroKid принимает музыку, созданную AI-инструментами, при наличии прав, запрете на имитацию других артистов, нарушение прав и массовый спам; при необходимости его поток загрузки просит указать AI credits. Изучите <a href="https://support.distrokid.com/hc/en-us/articles/41182362733715-Can-I-Upload-Music-Made-With-AI-Tools-to-DistroKid" className={linkClass} target="_blank" rel="noopener noreferrer">актуальную политику DistroKid об AI-музыке</a>.</p></div></section>
    <section className={section} id="gde-luchshe-vylozhit"><h2 className={heading}>Где лучше выложить первую ИИ-композицию</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Зависит от цели. Если важно просто начать, выберите один понятный маршрут и пройдите его полностью.</p><p>Стриминги – дистрибьютор. Видеоканал – YouTube. Страница композиции и каталог – можно начать с АудиоЛада.</p><p>Необязательно выбирать один путь навсегда – каталог может развиваться в нескольких направлениях.</p><p>Подробнее о модели заработка: <Link href="/kak-zarabatyvat-na-ii-muzyke-v-audiolad" className={linkClass}>Как зарабатывать на своей ИИ-музыке в АудиоЛаде</Link>.</p></div></section>
    <section className={section} id="faq"><h2 className={heading}>Частые вопросы</h2><ArticleFaqList items={KAK_VYLOZHIT_II_MUZYKU_FAQ} /></section>
  </article>;
}
