"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AudiobookChapter, AudiobookProject } from "@/lib/audiobooks/server";

async function request(url: string, init?: RequestInit) {
  const response = await fetch(url, init);
  if (!response.ok) throw new Error("request_failed");
  return response.status === 204 ? null : response.json();
}
export function AudiobookProjectWorkspace({ project, chapters: initialChapters, authorId }: { project: AudiobookProject; chapters: AudiobookChapter[]; authorId: string }) {
  const router = useRouter(); const [chapters, setChapters] = useState(initialChapters); const [selected, setSelected] = useState<string | null>(initialChapters[0]?.id ?? null); const [busy, setBusy] = useState(false);
  const base = `/api/studio/audiobooks/projects/${project.id}/chapters`;
  async function add() { const title = window.prompt("Название главы", `Глава ${chapters.length + 1}`)?.trim(); if (!title) return; setBusy(true); try { const { chapter } = await request(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorId, title }) }); setChapters([...chapters, chapter]); setSelected(chapter.id); } finally { setBusy(false); } }
  async function rename(chapter: AudiobookChapter) { const title = window.prompt("Название главы", chapter.title)?.trim(); if (!title) return; const { chapter: next } = await request(`${base}/${chapter.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorId, title }) }); setChapters(chapters.map((item) => item.id === next.id ? next : item)); }
  async function remove(chapter: AudiobookChapter) { if (!window.confirm(`Удалить главу?\n«${chapter.title}» будет удалена.`)) return; await request(`${base}/${chapter.id}?authorId=${authorId}`, { method: "DELETE" }); const next = chapters.filter((item) => item.id !== chapter.id).map((item, index) => ({ ...item, position: index + 1 })); setChapters(next); setSelected(next[0]?.id ?? null); }
  async function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= chapters.length) return; const next = [...chapters]; [next[index], next[target]] = [next[target], next[index]]; setBusy(true); try { const { chapters: saved } = await request(`${base}/reorder`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorId, chapterIds: next.map((item) => item.id) }) }); setChapters(saved); } finally { setBusy(false); } }
  async function renameBook() { const title = window.prompt("Название книги", project.title)?.trim(); if (!title) return; await request(`/api/studio/audiobooks/projects/${project.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorId, title }) }); router.refresh(); }
  const chapter = chapters.find((item) => item.id === selected);
  return <><header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/15 pb-6"><div><h1 className="text-3xl font-semibold">{project.title}</h1><button type="button" onClick={renameBook} className="mt-2 text-sm font-semibold text-[#9bdab5] underline">Переименовать книгу</button></div></header><section className="grid flex-1 gap-5 py-8 lg:grid-cols-[18rem_minmax(0,1fr)]"><aside className="rounded-[28px] border border-white/15 bg-[#21133d] p-6"><h2 className="text-xl font-semibold">Главы</h2><div className="mt-4 space-y-2">{chapters.map((item, index) => <div key={item.id} className={`rounded-xl p-3 ${selected === item.id ? "bg-[#4c3a6f]" : "bg-white/5"}`}><button type="button" onClick={() => setSelected(item.id)} className="w-full text-left text-sm">{item.position}. {item.title}</button><div className="mt-2 flex gap-2 text-xs text-[#ddd2f5]"><button disabled={busy || index === 0} onClick={() => move(index, -1)}>↑ Выше</button><button disabled={busy || index === chapters.length - 1} onClick={() => move(index, 1)}>↓ Ниже</button><button onClick={() => rename(item)}>Переименовать</button><button onClick={() => remove(item)}>Удалить</button></div></div>)}</div><button type="button" disabled={busy} onClick={add} className="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-full border border-[#8065ad] px-5 text-sm font-semibold text-white">+ Добавить главу</button></aside><section className="flex min-h-80 items-center justify-center rounded-[28px] border border-[#9074c7] bg-[#271647] p-6 text-center"><div><h2 className="text-2xl font-semibold">{chapter ? chapter.title : "Выберите главу"}</h2><p className="mt-4 leading-7 text-[#ddd2f5]">{chapter ? "Запись этой главы будет подключена на следующем этапе." : "После создания глав здесь появятся запись, прослушивание и работа с текстом."}</p></div></section></section></>;
}
