import Link from "next/link";
import type { ReactNode } from "react";

import ArticleFaqList from "@/components/articles/ArticleFaqList";
import { articleBodyStackClass } from "@/components/articles/typography";
import {
  DISTRIBYUTOR_II_MUZYKI_BREADCRUMB_TITLE,
  DISTRIBYUTOR_II_MUZYKI_FAQ,
  DISTRIBYUTOR_II_MUZYKI_HUB_HREF,
  DISTRIBYUTOR_II_MUZYKI_HUB_LABEL,
  DISTRIBYUTOR_II_MUZYKI_PAGE_H1,
} from "@/lib/seo/distribyutor-ii-muzyki";

const heading = "scroll-mt-24 text-2xl font-semibold tracking-tight text-[#25135c] sm:text-3xl";
const section = "mt-14 max-w-3xl sm:mt-20";
const visual = "mt-8 overflow-hidden rounded-[24px] border border-[#d8c8ee] bg-gradient-to-br from-[#fffaff] to-[#efe4fb] p-5 text-[#4a3d73] shadow-[0_12px_30px_rgba(90,60,145,0.08)] sm:p-7";
const hubLink = "font-medium text-[#7042c5] underline decoration-[#c9b6ea] underline-offset-4 hover:text-[#56318f]";

function Visual({ number, children, caption }: { number: string; children: ReactNode; caption: string }) {
  return <figure className={visual} data-visual-block={number}>{children}<figcaption className="mt-5 text-sm leading-6 text-[#6f6291]">{caption}</figcaption></figure>;
}

function FlowVisuals() {
  const card = "rounded-2xl border border-white/80 bg-white/85 px-3 py-3 text-center text-sm font-medium shadow-sm";
  return (
    <>
      <Visual number="1" caption="Выберите подходящий канал для готовой музыкальной работы.">
        <div className="grid gap-4 sm:grid-cols-[1.1fr_1.6fr] sm:items-center">
          <div className="rounded-3xl bg-[#7042c5] p-5 text-center text-white"><svg viewBox="0 0 96 52" className="mx-auto h-10 w-20" fill="none" aria-hidden="true"><path d="M4 32c10 0 10-14 20-14s10 20 20 20 10-28 20-28 10 14 28 14" stroke="currentColor" strokeWidth="4" strokeLinecap="round" /><path d="M69 5v22m0-22 17-4v22" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" /><circle cx="63" cy="31" r="5" fill="currentColor" /><circle cx="80" cy="27" r="5" fill="currentColor" /></svg><div className="mt-2 font-semibold">Автор и музыка</div><div className="mt-1 text-sm text-white/80">ноутбук, идея, волна</div></div>
          <div><p className="mb-3 text-center text-sm font-semibold uppercase tracking-[0.12em] text-[#7042c5]">Куда загружать ИИ-музыку?</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{["Яндекс Музыка", "VK Музыка", "Spotify", "YouTube Music", "АудиоЛад"].map((label) => <div key={label} className={card}>{label}</div>)}</div></div>
        </div>
      </Visual>
      <Visual number="2" caption="Загрузили релиз один раз – дистрибьютор доставляет его на выбранные музыкальные площадки.">
        <div className="grid gap-3 text-center text-sm sm:grid-cols-[1fr_auto_1.2fr_auto_1.5fr] sm:items-center"><div className={card}>Автор<br /><b>«Моя музыка»</b></div><div className="text-xl text-[#7042c5]">→</div><div className="rounded-2xl border border-[#c9b6ea] bg-[#efe4fb] px-4 py-5 font-semibold">Склад<br />Музыкальный дистрибьютор</div><div className="text-xl text-[#7042c5]">→</div><div className="grid grid-cols-2 gap-2"><div className={card}>Яндекс Музыка</div><div className={card}>VK Музыка</div><div className={card}>Spotify</div><div className={card}>Apple Music</div><div className={`${card} col-span-2`}>YouTube Music</div></div></div>
      </Visual>
      <Visual number="3" caption="Одна музыка – несколько каналов распространения.">
        <div className="grid gap-3 text-center sm:grid-cols-[1fr_auto_2fr] sm:items-center"><div className="rounded-3xl bg-[#7042c5] px-4 py-6 font-semibold text-white">Одна композиция<br /><span className="text-sm font-normal text-white/80">ваша нейромузыка</span></div><div className="text-xl text-[#7042c5]">→</div><div className="grid gap-2 sm:grid-cols-3"><div className={card}>Стриминговые сервисы</div><div className={card}>YouTube</div><div className={card}>Прямая продажа<br />АудиоЛад</div></div></div>
      </Visual>
      <Visual number="4" caption="Не нужен один часовой трек – длинный музыкальный продукт можно собрать из нескольких коротких композиций.">
        <div className="grid gap-4 sm:grid-cols-[1.8fr_auto_1fr] sm:items-center"><div className="flex flex-wrap justify-center gap-2">{["3:20", "4:10", "3:45", "4:05", "3:30", "4:20"].map((time) => <span key={time} className="rounded-full border border-[#c9b6ea] bg-white px-3 py-2 text-sm font-medium">{time}</span>)}</div><div className="text-xl text-[#7042c5]">→</div><div className="rounded-2xl bg-[#7042c5] px-4 py-5 text-center font-semibold text-white">Альбом<br /><span className="text-sm font-normal text-white/80">Музыка для массажа – 60 минут</span></div></div>
      </Visual>
    </>
  );
}

export default function DistribyutorIiMuzykiPageView() {
  return <article className="pb-16 pt-4">
    <nav aria-label="Хлебные крошки" className="text-sm text-[#7d70a2]"><ol className="flex flex-wrap gap-1.5"><li><Link href="/" className={hubLink}>Главная</Link></li><li>/</li><li><Link href="/for-authors" className={hubLink}>Авторам</Link></li><li>/</li><li aria-current="page">{DISTRIBYUTOR_II_MUZYKI_BREADCRUMB_TITLE}</li></ol></nav>
    <header className="mt-8 max-w-3xl sm:mt-10"><h1 className="text-[1.85rem] font-semibold leading-tight tracking-tight text-[#25135c] sm:text-4xl">{DISTRIBYUTOR_II_MUZYKI_PAGE_H1}</h1>
      <div className={`mt-7 ${articleBodyStackClass}`}><p>Создать музыку с помощью нейросети сегодня можно довольно быстро. Но когда первый хороший трек уже готов, появляется следующий вопрос:</p><p className="font-semibold text-[#25135c]">А что теперь с ним делать?</p><p>Как попасть в Яндекс Музыку, VK Музыку, Spotify, Apple Music или YouTube Music? Куда загружать трек? Нужен ли для этого специальный сервис? Можно ли продавать музыку напрямую? И чем музыкальный дистрибьютор отличается от площадки, где автор сам размещает свою музыку?</p><p>Разберём всё простыми словами.</p></div>
    </header>
    <FlowVisuals />
    <section className={section} id="korotko"><h2 className={heading}>Коротко</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Если ваша задача – разместить музыку на стриминговых сервисах, например в Яндекс Музыке, VK Музыке, Spotify, Apple Music или YouTube Music, обычно для этого нужен музыкальный дистрибьютор.</p><p>Вы один раз загружаете релиз дистрибьютору, а он передаёт его на выбранные музыкальные площадки.</p><p>Если вы ищете, где публиковать ИИ музыку, где разместить нейромузыку или как выложить ИИ музыку, сначала определите задачу: загрузить ИИ музыку в стриминг, показать её на YouTube или предложить слушателю как готовый продукт. Дистрибьютор AI музыки помогает с первым вариантом.</p><p>Если же вы хотите продавать свою нейромузыку непосредственно слушателям, создавать собственный каталог музыкальных продуктов и получать деньги за отдельные треки или альбомы, можно использовать специализированные музыкальные платформы и маркетплейсы.</p><p>Например, в АудиоЛаде автор может опубликовать ИИ-музыку как самостоятельный аудиопродукт, который покупают слушатели. Эта же музыка может дополнительно использоваться авторами медитаций и аудиопрактик в своих проектах.</p><p><Link href={DISTRIBYUTOR_II_MUZYKI_HUB_HREF} className={hubLink}>{DISTRIBYUTOR_II_MUZYKI_HUB_LABEL}</Link></p></div></section>
    <section className={section} id="chto-takoe"><h2 className={heading}>Что такое музыкальный дистрибьютор</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Музыкальный дистрибьютор – это сервис-посредник между автором музыки и большими музыкальными площадками.</p><p>Представьте большой склад. Вы один раз привозите на этот склад свою музыку. А дальше со склада она развозится «маленькими грузовичками» по разным цифровым магазинам и стриминговым сервисам – в Spotify, YouTube Music, Яндекс Музыку, VK Музыку, Apple Music и другие площадки.</p><p>Примерно так и работает музыкальная дистрибуция.</p><p className="font-semibold text-[#25135c]">Автор → музыкальный дистрибьютор → стриминговые сервисы → слушатели</p><p>Вам не нужно самостоятельно загружать один и тот же альбом в несколько разных сервисов. Вы заходите в кабинет дистрибьютора, загружаете музыку, обложку, указываете название сингла или альбома, имя исполнителя и другую информацию о релизе. Дальше дистрибьютор отправляет музыку на выбранные вами площадки.</p></div></section>
    <section className={section} id="kakie-distribyutory"><h2 className={heading}>Какие музыкальные дистрибьюторы существуют</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Музыкальных дистрибьюторов много. Среди известных международных сервисов можно назвать, например: <b>DistroKid, TuneCore и ONErpm.</b></p><p>Есть и сервисы, через которые можно размещать музыку в российских стримингах. Среди партнёров и сервисов, работающих с российским рынком, встречаются, например: <b>FreshTunes, Multiza, MusicAlligator, Electronic Music Distribution, ONErpm, DNK Music, ZVONKO digital, Believe Digital и другие.</b></p><p>То есть музыкальный дистрибьютор – это не название какой-то одной компании. Это целый тип сервисов.</p><p>Автор выбирает дистрибьютора в зависимости от того:</p><ul><li>на какие площадки он хочет попасть;</li><li>с какими странами работает сервис;</li><li>сколько стоит размещение;</li><li>как устроены выплаты;</li><li>какие требования предъявляются к релизам;</li><li>принимает ли сервис музыку, созданную с помощью ИИ.</li></ul></div></section>
    <section className={section} id="ai-distribyutor"><h2 className={heading}>А что такое дистрибьютор ИИ-музыки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>По сути, это обычный музыкальный дистрибьютор, через которого автор размещает музыку, созданную полностью или частично с помощью нейросетей. Например: Suno; Udio; другие AI-сервисы для создания музыки; нейросети для отдельных элементов композиции.</p><p>Но здесь появляется дополнительный вопрос: <b>разрешает ли конкретный дистрибьютор AI-контент?</b></p><p>У разных сервисов могут быть свои правила. Например, DistroKid сейчас разрешает музыку, созданную с помощью AI-инструментов, если у автора есть необходимые права и релиз соответствует требованиям сервиса и стриминговых площадок.</p><p>Поэтому перед публикацией нейромузыки лучше проверить правила именно того дистрибьютора, которого вы выбрали. И проверять их стоит непосредственно перед загрузкой релиза – требования сервисов могут меняться.</p></div></section>
    <section className={section} id="mozhno-li-publikovat"><h2 className={heading}>Можно ли публиковать музыку, созданную ИИ</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Сам факт использования нейросети ещё не означает, что музыку нельзя публиковать. Главный вопрос – какими правами на получившуюся композицию располагаете вы сами.</p><p>Это может зависеть от: AI-сервиса; тарифа; условий использования; исходных материалов; голосов; семплов; правил дистрибьютора; требований конечной площадки.</p><p>Например, условия бесплатного и платного тарифа одного и того же сервиса могут отличаться. Поэтому перед коммерческой публикацией лучше проверить, разрешают ли условия конкретного AI-сервиса распространять и монетизировать созданную вами музыку.</p></div></section>
    <section className={section} id="gde-publikovat"><h2 className={heading}>Где можно публиковать ИИ-музыку</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Автору совершенно не обязательно выбирать только один способ. У одной и той же музыки может быть несколько каналов распространения.</p><h3 className="text-xl font-semibold text-[#25135c]">1. Стриминговые сервисы</h3><p>Яндекс Музыка, VK Музыка, Spotify, Apple Music, YouTube Music и другие. Обычно релиз попадает туда через музыкального дистрибьютора. Можно выпустить сингл, несколько синглов, EP или альбом. Доход обычно связан с прослушиваниями и системой выплат сервисов и дистрибьютора.</p><h3 className="text-xl font-semibold text-[#25135c]">2. YouTube</h3><p>Музыку можно публиковать как видеоконтент: музыка для сна; relaxing music; jazz ambience; концентрация; работа; SPA; массаж; медитация; йога; кафе. Из одной библиотеки можно создать тематический канал.</p><h3 className="text-xl font-semibold text-[#25135c]">3. Прямая продажа музыки</h3><p>Музыку можно превратить в самостоятельный цифровой продукт. Человек ищет конкретное решение: «Музыка для массажа», «Медитация для сна без слов», «Спокойная музыка для работы и концентрации» – и покупает доступ к этому продукту.</p></div></section>
    <section className={section} id="audiolad"><h2 className={heading}>Чем АудиоЛад отличается от музыкального дистрибьютора</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>АудиоЛад – не классический музыкальный дистрибьютор, который отправляет релиз в Spotify или Яндекс Музыку. АудиоЛад – платформа и маркетплейс аудиопродуктов.</p><p className="font-semibold text-[#25135c]">Автор → АудиоЛад → слушатель</p><p>У музыкальной работы есть страница, название, обложка, описание, автор, цена, плеер. Слушатель может купить прямо на платформе.</p><p>Дополнительно авторы медитаций и аудиопрактик могут платно использовать музыку в своих проектах внутри Студии АудиоЛада. Два источника дохода: слушатели покупают; авторы медитаций и аудиопрактик используют.</p><p><Link href={DISTRIBYUTOR_II_MUZYKI_HUB_HREF} className={hubLink}>{DISTRIBYUTOR_II_MUZYKI_HUB_LABEL}</Link></p></div></section>
    <section className={section} id="vybor"><h2 className={heading}>Нужно ли выбирать между дистрибьютором и АудиоЛадом</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Нет. Это разные инструменты. Один альбом можно выпустить через дистрибьютора, использовать для YouTube и оформить как продукты на АудиоЛаде. Главное – права и правила сервисов.</p><h2 className={heading}>Стриминг и прямая продажа музыки – в чём разница</h2><p>Стриминг – это доступ к библиотеке, прослушивания и выплаты по правилам сервиса. При прямой продаже пользователь покупает конкретный продукт: «мне нужна именно эта музыка». Эти модели дополняют друг друга.</p></div></section>
    <section className={section} id="dlinnyy-trek"><h2 className={heading}>Нужно ли создавать один длинный трек</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Нет. Длинный продукт может состоять из нескольких коротких композиций. Это подходит для сна, массажа, SPA, йоги, дыхания, медитации, работы или кафе.</p><p>Час для массажа можно собрать из 10–15 треков по несколько минут. Особенно удобно для Suno. Задача не «создать один часовой трек», а «создать 10–15 хороших композиций и собрать часовую программу».</p></div></section>
    <section className={section} id="katalog"><h2 className={heading}>Почему назначение музыки важно</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>«Moonlight Dreams» и «Спокойная музыка для массажа» отвечают на разное поисковое намерение. Люди ищут музыку для сна, массажа, SPA, медитации, йоги, работы и концентрации, спокойную фоновую музыку. Из нейромузыки можно строить тематический каталог.</p><h2 className={heading}>Как подготовить ИИ-музыку к публикации</h2><p>Оформите название, обложку, описание, продолжительность, например «Музыка для массажа – 60 минут», структуру из 10 композиций по 6 минут или 15 коротких работ, проверьте права и поисковое намерение.</p><h2 className={heading}>Можно ли сделать из нейромузыки большой каталог</h2><p>Да. 50, 100, 300 работ, альбомы, отдельные публикации, длинные программы. У каждой работы есть название, обложка, описание, назначение, страница и слушатели. Каталог даёт точки входа во времени.</p></div></section>
    <section className={section} id="faq"><h2 className={heading}>Частые вопросы</h2><ArticleFaqList items={DISTRIBYUTOR_II_MUZYKI_FAQ} /></section>
    <section className={`${section} rounded-[28px] border border-[#d8c8ee] bg-[#faf7ff] p-6 sm:p-8`} id="start"><h2 className={heading}>С чего начать</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Начните с одной работы. Создали музыку → оформили → выбрали способ распространения → опубликовали.</p><p>Для этого можно выбрать дистрибьютора, YouTube или платформу прямой продажи. Не нужно сразу создавать большой каталог: начните с одной законченной музыкальной работы и постепенно добавляйте новые.</p><p><Link href={DISTRIBYUTOR_II_MUZYKI_HUB_HREF} className={hubLink}>{DISTRIBYUTOR_II_MUZYKI_HUB_LABEL}</Link></p></div></section>
  </article>;
}
