export {
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_BREADCRUMB_TITLE,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_DATE_PUBLISHED,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_FAQ,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_PAGE_H1,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_PATH,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_SEO_DESCRIPTION,
  KAK_PRODAT_MUZYKU_SOZDANNUYU_II_SEO_TITLE,
  type KakProdatMuzykuSozdannuyuIiFaqItem,
} from "./content";
