import Link from "next/link";
import type { ReactNode } from "react";

import AiMusicIntroCta from "@/components/ai-music/AiMusicIntroCta";
import ArticleFaqList from "@/components/articles/ArticleFaqList";
import { articleBodyStackClass } from "@/components/articles/typography";
import {
  V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_BREADCRUMB_TITLE,
  V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_FAQ,
  V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_PAGE_H1,
} from "@/lib/seo/v-kakoy-neyroseti-sozdat-muzyku";

const heading = "scroll-mt-24 text-2xl font-semibold tracking-tight text-[#25135c] sm:text-3xl";
const section = "mt-14 max-w-3xl sm:mt-20";
const visual = "mt-8 overflow-hidden rounded-[24px] border border-[#d8c8ee] bg-gradient-to-br from-[#fffaff] to-[#efe4fb] p-5 text-[#4a3d73] shadow-[0_12px_30px_rgba(90,60,145,0.08)] sm:p-7";
const linkClass = "font-medium text-[#7042c5] underline decoration-[#c9b6ea] underline-offset-4 hover:text-[#56318f]";
const card = "rounded-2xl border border-white/80 bg-white/85 px-3 py-3 text-center text-sm font-medium shadow-sm";

function Visual({ number, children, caption }: { number: string; children: ReactNode; caption: string }) {
  return <figure className={visual} data-visual-block={number}>{children}<figcaption className="mt-5 text-sm leading-6 text-[#6f6291]">{caption}</figcaption></figure>;
}

function TaskVisual() {
  return <Visual number="1" caption="Выбор начинается не с рейтинга сервисов, а с задачи, для которой нужна музыка."><div className="grid gap-3 text-center sm:grid-cols-[1fr_auto_2fr_auto_1fr] sm:items-center"><div className="rounded-3xl bg-[#7042c5] px-4 py-6 font-semibold text-white">Хочу создать<br />музыку</div><div className="text-xl text-[#7042c5]">→</div><div className="grid grid-cols-2 gap-2">{["Песня с вокалом", "Инструментальная", "Фон для видео", "Эксперименты и редактура"].map((item) => <div className={card} key={item}>{item}</div>)}</div><div className="text-xl text-[#7042c5]">→</div><div className="rounded-3xl border border-[#c9b6ea] bg-white px-4 py-6 font-semibold">Выбираем сервис<br />под задачу</div></div></Visual>;
}

function SunoUdioVisual() {
  return <Visual number="2" caption="Suno и Udio помогают искать музыкальные варианты, но текущая возможность скачать результат у сервисов различается."><div className="grid gap-3 text-center sm:grid-cols-2"><div className="rounded-2xl border border-[#c9b6ea] bg-white p-4"><p className="font-semibold text-[#25135c]">Suno</p><p className="mt-2 text-sm">Идея → генерация → варианты → проверка плана и прав</p></div><div className="rounded-2xl border border-[#c9b6ea] bg-white p-4"><p className="font-semibold text-[#25135c]">Udio</p><p className="mt-2 text-sm">Идея → генерация → варианты → проверка текущего статуса сервиса</p></div><div className="rounded-2xl bg-[#7042c5] px-4 py-3 text-sm font-medium text-white sm:col-span-2">Экспорт и скачивание: Suno зависит от плана; в Udio скачивание аудио, видео и стемов сейчас отключено.</div></div></Visual>;
}

function ChoiceVisual() {
  return <Visual number="3" caption="Один и тот же запрос приводит к разным сервисам, когда меняется ожидаемый результат."><div className="text-center"><p className="font-semibold text-[#25135c]">Что вы хотите получить?</p><div className="mt-4 grid gap-2 sm:grid-cols-4">{[["Suno", "Песня, вокал, первые варианты"], ["Udio", "Песни, варианты, эксперименты"], ["Loudly", "Управляемая фоновая музыка"], ["Mubert", "Музыка внутри контента"]].map(([name, text]) => <div className={card} key={name}><span className="block font-semibold text-[#25135c]">{name}</span><span className="mt-1 block text-xs font-normal">{text}</span></div>)}</div></div></Visual>;
}

function RightsVisual() {
  return <Visual number="4" caption="Перед публикацией или продажей нужно отдельно проверить, разрешает ли условиями сервиса выбранный сценарий использования."><div className="grid gap-3 text-center sm:grid-cols-[1fr_auto_1fr_auto_2fr] sm:items-center"><div className={card}>Нейросеть</div><div className="text-xl text-[#7042c5]">→</div><div className={card}>Готовый трек</div><div className="text-xl text-[#7042c5]">→</div><div className="grid grid-cols-3 gap-2"><div className={card}>Слушать</div><div className={card}>Публиковать</div><div className={card}>Продавать</div><div className={`${card} col-span-3 border-[#7042c5]`}>Разрешено ли условиями сервиса?</div></div></div></Visual>;
}

export default function VKakoyNeyrosetiSozdatMuzykuPageView() {
  return <article className="pb-16 pt-4">
    <nav aria-label="Хлебные крошки" className="text-sm text-[#7d70a2]"><ol className="flex flex-wrap gap-1.5"><li><Link href="/" className={linkClass}>Главная</Link></li><li>/</li><li><Link href="/for-authors" className={linkClass}>Авторам</Link></li><li>/</li><li aria-current="page">{V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_BREADCRUMB_TITLE}</li></ol></nav>
    <header className="mt-8 max-w-3xl sm:mt-10"><h1 className="text-[1.85rem] font-semibold leading-tight tracking-tight text-[#25135c] sm:text-4xl">{V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_PAGE_H1}</h1><div className={`mt-7 ${articleBodyStackClass}`}><p>Музыкальных нейросетей становится всё больше. Одни делают песни с вокалом, другие помогают получить инструментальный фон для видео, третьи дают больше параметров для работы с темпом, структурой и звуком.</p><p>Поэтому вопрос начинающего автора обычно звучит не «какой сервис лучший вообще», а иначе:</p><p className="font-semibold text-[#25135c]">в какой нейросети мне создать музыку для моей задачи?</p><p>Эта статья поможет выбрать сервис под нужный результат. Если вы уже выбрали инструмент и хотите разобраться в самом процессе генерации, откройте материал <Link href="/kak-sozdat-ii-muzyku" className={linkClass}>«Как создать ИИ-музыку с помощью нейросети: пошаговая инструкция»</Link>.</p></div></header>
    <TaskVisual />
    <section className={section} id="korotko"><h2 className={heading}>Коротко: какую нейросеть выбрать</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Suno удобно рассматривать, когда нужна песня с вокалом, текстом или быстрые первые музыкальные варианты. Udio подходит для песен, вариантов и экспериментов, однако на момент публикации скачивание результатов там отключено.</p><p>Loudly полезен для управляемой инструментальной и фоновой музыки: можно задавать жанр, поджанр, BPM, тональность, энергию, инструменты, структуру и длительность. Mubert лучше воспринимать как сервис лицензируемой музыки внутри контента, а не как путь к самостоятельному релизу на стримингах.</p><p>Яндекс Нейромузыка стоит отдельно: это персонализированный поток для прослушивания, а не сервис для создания своего скачиваемого трека.</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className={card}><b>Suno</b><br />Песня с вокалом и первые генерации</div><div className={card}><b>Udio</b><br />Варианты и музыкальные эксперименты</div><div className={card}><b>Loudly</b><br />Фоновая музыка с параметрами</div><div className={card}><b>Mubert</b><br />Музыка для контента по лицензии</div></div></section>
    <section className={section} id="suno"><h2 className={heading}>Suno – для песен с вокалом и первых идей</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Suno подойдёт, когда хочется быстро проверить музыкальную идею, получить песню с вокалом или сравнить несколько направлений. Сервис можно попробовать бесплатно, но это не то же самое, что право использовать трек в коммерции.</p><p>По <a href="https://help.suno.com/en/articles/9601601" className={linkClass} target="_blank" rel="noopener noreferrer">правилам бесплатного плана Suno</a>, созданные на нём песни предназначены для личного некоммерческого использования: их нельзя монетизировать, но можно делиться ссылкой Suno.</p><p><a href="https://help.suno.com/en/articles/2410177" className={linkClass} target="_blank" rel="noopener noreferrer">Коммерческие права Suno</a> даёт для песен, созданных во время подписки Pro или Premier. Подписка, оформленная позже, не даёт коммерческую лицензию задним числом для бесплатного трека. Поэтому если вы планируете продажу, рекламу или публикацию с монетизацией, проверяйте план до генерации и сверяйтесь с <a href="https://www.suno.com/terms-september-2026" className={linkClass} target="_blank" rel="noopener noreferrer">актуальными условиями Suno</a>.</p><p>Отдельно учитывайте скачивание: на странице <a href="https://suno.com/pricing" className={linkClass} target="_blank" rel="noopener noreferrer">тарифов Suno</a> указаны ограничения на загрузки, включая отсутствие ежемесячных скачиваний на Free начиная с 3 сентября 2026 года и месячные лимиты на Pro и Premier.</p></div></section>
    <section className={section} id="udio"><h2 className={heading}>Udio – для песен, вариантов и музыкальных экспериментов</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Udio можно рассматривать как пространство для поиска музыкальных вариантов и экспериментов с идеей. Но выбор сервиса зависит не только от того, нравится ли результат в браузере, а и от возможности использовать его дальше.</p><h3 className="text-xl font-semibold text-[#25135c]">Что важно знать сейчас</h3><p>В справке Udio от 17 февраля 2026 года указано, что в период изменений, связанных с партнёрством с Universal Music Group, скачивание аудио, видео и стемов отключено. Это означает, что сейчас Udio нельзя выбирать для задачи, где нужен экспорт готового файла. Проверяйте <a href="https://help.udio.com/en/articles/12683565-changes-associated-with-the-universal-music-group-umg-partnership" className={linkClass} target="_blank" rel="noopener noreferrer">текущий статус загрузок в официальной справке Udio</a> перед работой.</p><p>Если вам важны именно генерации, варианты и исследование звучания, сервис может быть полезен. Если дальше нужен скачиваемый трек для монтажа, публикации или дистрибуции, сначала убедитесь, что статус экспорта изменился.</p></div></section>
    <SunoUdioVisual />
    <section className={section} id="loudly"><h2 className={heading}>Loudly – для фоновой музыки и точного управления параметрами</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Loudly стоит выбирать, когда музыка должна решать прикладную задачу: стать фоном для ролика, подкаста, игры, рекламы или другого контента. В генераторе можно направлять результат жанром и поджанром, BPM, тональностью, энергией, инструментами, структурой и длительностью.</p><p>Сервис заявляет возможность скачивать WAV, MP3 и стемы. Эти параметры особенно полезны, когда музыка должна попасть в конкретную длину видео, темп монтажа или звуковую палитру проекта. Возможности описаны на <a href="https://www.loudly.com/ai-music-generator" className={linkClass} target="_blank" rel="noopener noreferrer">странице AI Music Generator Loudly</a>.</p><p>Loudly говорит о royalty-free и коммерческой лицензии, но сценарий использования всё равно нужно сверять с тарифом и условиями. Для выпуска через дистрибуцию Loudly отсылает к собственному разделу об <a href="https://www.loudly.com/knowledge-base/ai-music-distribution" className={linkClass} target="_blank" rel="noopener noreferrer">AI Music Distribution</a>. Не считайте бесплатный доступ универсальным правом перепродавать результат где угодно.</p></div></section>
    <section className={section} id="mubert"><h2 className={heading}>Mubert – для музыки внутри видео, подкастов и других проектов</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Mubert Render предназначен для создания музыки под контент и лицензирования такого использования. Он полезен, когда нужен фон для видео, канала, подкаста, игры или приложения, а не самостоятельный релиз артиста.</p><p>В <a href="https://mubert.com/render/faq" className={linkClass} target="_blank" rel="noopener noreferrer">FAQ Mubert</a> сказано, что созданные треки нельзя выпускать как самостоятельную музыку на DSP, например Spotify или Apple Music, и нельзя регистрировать в Content ID. При этом музыка может использоваться как фон внутри YouTube-видео в пределах условий плана.</p><p>Условия различаются: бесплатный Ambassador рассчитан на личные проекты, а коммерческое использование и монетизация требуют подходящего плана. Перед запуском кампании или публикацией проверьте <a href="https://mubert.com/render/pricing" className={linkClass} target="_blank" rel="noopener noreferrer">тарифы Mubert Render</a> и лицензионный сценарий.</p></div></section>
    <section className={section} id="yandex-neuromusic"><h2 className={heading}>Яндекс Нейромузыка – не генератор для авторского релиза</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Яндекс Нейромузыка не является прямым аналогом Suno, Udio, Loudly или Mubert. Официально это бесконечная персонализированная мелодия для прослушивания, которую алгоритмы генерируют в реальном времени.</p><p>У сервиса есть режимы «Спокойствие», «Вдохновение» и «Бодрость». Он создан для концентрации, работы, учёбы, чтения и тренировок. В <a href="https://yandex.ru/company/news/02-08-2022" className={linkClass} target="_blank" rel="noopener noreferrer">новости Яндекса</a> нет функции создания пользователем собственного трека по промпту с последующим скачиванием и выпуском.</p><p>Поэтому Нейромузыка может быть вариантом для слушателя, но не для автора, который выбирает инструмент для создания и публикации своей композиции.</p></div></section>
    <ChoiceVisual />
    <section className={section} id="dlya-nachinayushchego"><h2 className={heading}>Какая нейросеть лучше для начинающего</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Нет одного правильного ответа для всех. Начинающему проще выбрать одну конкретную цель и проверить сервис именно на ней.</p><ul><li>Нужна первая песня с вокалом или музыкальная идея – начните с Suno.</li><li>Нужны варианты и эксперименты со звучанием – рассмотрите Udio, помня о текущем отсутствии скачивания.</li><li>Нужен контролируемый инструментальный фон для проекта – посмотрите Loudly.</li><li>Нужна музыка именно внутри видео или другого контента – изучите Mubert и его лицензию.</li></ul><p>Не нужно сразу оплачивать несколько подписок. Сначала сформулируйте один сценарий, сделайте несколько тестовых вариантов и оцените не только звучание, но и возможность законно использовать результат дальше.</p></div></section>
    <section className={section} id="ne-po-odnomu-treku"><h2 className={heading}>Не выбирайте сервис только по одному треку</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Одна удачная генерация может создать ложное впечатление. Сравните несколько результатов на одном и том же кратком задании: качество начала и финала, соответствие настроению, повторяемость нужного направления, понятность интерфейса и доступные способы сохранения.</p><p>Для песни важны вокал, мелодия и работа с текстом. Для фона – длительность, темп, плотность аранжировки и возможность встроить результат в монтаж. Для публикации важнее всего права, экспорт и правила площадки назначения.</p></div></section>
    <section className={section} id="sudba-muzyki"><h2 className={heading}>Сначала определите дальнейшую судьбу музыки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>До первой генерации ответьте на вопрос: что произойдёт с треком после того, как он будет готов?</p><p>Можно просто слушать его самому. Можно поставить фоном в своё видео. Можно опубликовать как самостоятельную композицию. Можно попытаться продавать музыку или использовать её в коммерческом проекте. Эти маршруты требуют разных прав.</p><p>Особенно внимательно отнеситесь к Suno: бесплатный режим позволяет попробовать генерацию, но не монетизацию. У Mubert лицензия ориентирована на фон внутри контента, а не на самостоятельный стриминговый релиз. Условия сервисов меняются, поэтому сохраняйте сведения о плане, дате создания и документах, которые действовали для вашего трека.</p></div></section>
    <RightsVisual />
    <AiMusicIntroCta paragraphs={["Даже если вы пока только выбираете нейросеть и делаете первые музыкальные эксперименты, загляните в АудиоЛад. Послушайте музыку и аудиопрактики, посмотрите, как оформлены музыкальные продукты и какие возможности есть у авторов.", "Можно зарегистрироваться бесплатно, познакомиться с площадкой как слушатель и автор и вернуться к публикации своей музыки тогда, когда у вас появятся готовые композиции."]} />
    <section className={section} id="posle-vybora"><h2 className={heading}>Что делать после выбора</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Выберите один сервис под свою задачу, сделайте несколько вариантов и отберите те, которые действительно хотите сохранить. До публикации проверьте права на конкретный трек, условия вашего плана и ограничения площадки, куда он отправится.</p><p>Когда композиция готова к выходу, переходите к следующему этапу: <Link href="/kak-vylozhit-ii-muzyku" className={linkClass}>как выложить ИИ-музыку</Link>. Если речь идёт о распространении на стримингах, изучите материал <Link href="/distribyutor-ii-muzyki" className={linkClass}>о дистрибьюторе ИИ-музыки</Link>. Для коммерческой модели на платформе смотрите <Link href="/kak-zarabatyvat-na-ii-muzyke-v-audiolad" className={linkClass}>как зарабатывать на своей ИИ-музыке в АудиоЛаде</Link>.</p></div></section>
    <section className={section} id="faq"><h2 className={heading}>Частые вопросы</h2><ArticleFaqList items={V_KAKOY_NEYROSETI_SOZDAT_MUZYKU_FAQ} /></section>
  </article>;
}
