import Link from "next/link";
import type { ReactNode } from "react";

import AiMusicIntroCta from "@/components/ai-music/AiMusicIntroCta";
import ArticleFaqList from "@/components/articles/ArticleFaqList";
import { articleBodyStackClass } from "@/components/articles/typography";
import {
  KAK_SOZDAT_II_MUZYKU_BREADCRUMB_TITLE,
  KAK_SOZDAT_II_MUZYKU_FAQ,
  KAK_SOZDAT_II_MUZYKU_PAGE_H1,
} from "@/lib/seo/kak-sozdat-ii-muzyku";

const heading = "scroll-mt-24 text-2xl font-semibold tracking-tight text-[#25135c] sm:text-3xl";
const section = "mt-14 max-w-3xl sm:mt-20";
const visual = "mt-8 overflow-hidden rounded-[24px] border border-[#d8c8ee] bg-gradient-to-br from-[#fffaff] to-[#efe4fb] p-5 text-[#4a3d73] shadow-[0_12px_30px_rgba(90,60,145,0.08)] sm:p-7";
const linkClass = "font-medium text-[#7042c5] underline decoration-[#c9b6ea] underline-offset-4 hover:text-[#56318f]";
const card = "rounded-2xl border border-white/80 bg-white/85 px-3 py-3 text-center text-sm font-medium shadow-sm";

function Visual({ number, children, caption }: { number: string; children: ReactNode; caption: string }) {
  return <figure className={visual} data-visual-block={number}>{children}<figcaption className="mt-5 text-sm leading-6 text-[#6f6291]">{caption}</figcaption></figure>;
}

function CreationFlowVisual() {
  return <Visual number="1" caption="Создание ИИ-музыки – это последовательность от идеи и описания до выбора готового трека."><div className="grid gap-2 text-center text-sm font-semibold sm:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr_auto_1fr] sm:items-center">{["Идея", "Промпт", "Нейросеть", "Варианты", "Трек"].map((item, index) => <div className="contents" key={item}><div className={index === 2 ? "rounded-2xl bg-[#7042c5] px-3 py-4 text-white shadow-sm" : card}>{item}</div>{index < 4 && <div className="text-xl text-[#7042c5]">→</div>}</div>)}</div></Visual>;
}

function PromptVisual() {
  return <Visual number="2" caption="Чем точнее вы описываете задачу, тем проще нейросети приблизиться к нужному звучанию."><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="grid grid-cols-2 gap-2 sm:grid-cols-1">{["Назначение", "Настроение", "Инструменты", "Темп", "Вокал / без вокала"].map((item) => <div className={card} key={item}>{item}</div>)}</div><div className="text-center text-xl text-[#7042c5]">→</div><div className="rounded-3xl bg-[#7042c5] p-6 text-center font-semibold text-white">Понятный<br />музыкальный запрос</div></div></Visual>;
}

function VariantsVisual() {
  return <Visual number="3" caption="Одна идея может дать несколько разных результатов – сравните варианты и выберите самый удачный."><div className="grid gap-4 sm:grid-cols-[1fr_auto_1.5fr] sm:items-center"><div className="rounded-2xl border border-[#c9b6ea] bg-white p-4 text-center font-semibold">Спокойная музыка<br />для массажа</div><div className="text-center text-xl text-[#7042c5]">→</div><div className="grid grid-cols-2 gap-2">{["Вариант 1", "Вариант 2", "Вариант 3", "Вариант 4"].map((item) => <div className={item === "Вариант 4" ? "rounded-2xl bg-[#7042c5] px-3 py-4 text-center text-sm font-semibold text-white" : card} key={item}>{item}{item === "Вариант 4" && <span className="mt-1 block text-xs font-normal text-white/80">Выбран лучший</span>}</div>)}</div></div></Visual>;
}

function HourVisual() {
  return <Visual number="4" caption="Часовой музыкальный продукт можно собрать из серии коротких качественных композиций."><div className="grid gap-4 sm:grid-cols-[1.8fr_auto_1fr] sm:items-center"><div className="flex flex-wrap justify-center gap-2">{["5:48", "6:12", "5:56", "6:04", "5:52", "6:08", "5:59", "6:01", "5:54", "6:06"].map((time) => <span className="rounded-full border border-[#c9b6ea] bg-white px-2.5 py-2 text-sm font-medium" key={time}>{time}</span>)}</div><div className="text-center text-xl text-[#7042c5]">→</div><div className="rounded-2xl bg-[#7042c5] px-4 py-5 text-center font-semibold text-white">Музыка для массажа<br /><span className="text-sm font-normal text-white/80">≈ 60 минут</span></div></div></Visual>;
}

export default function KakSozdatIiMuzykuPageView() {
  return <article className="pb-16 pt-4">
    <nav aria-label="Хлебные крошки" className="text-sm text-[#7d70a2]"><ol className="flex flex-wrap gap-1.5"><li><Link href="/" className={linkClass}>Главная</Link></li><li>/</li><li><Link href="/for-authors" className={linkClass}>Авторам</Link></li><li>/</li><li aria-current="page">{KAK_SOZDAT_II_MUZYKU_BREADCRUMB_TITLE}</li></ol></nav>
    <header className="mt-8 max-w-3xl sm:mt-10"><h1 className="text-[1.85rem] font-semibold leading-tight tracking-tight text-[#25135c] sm:text-4xl">{KAK_SOZDAT_II_MUZYKU_PAGE_H1}</h1><div className={`mt-7 ${articleBodyStackClass}`}><p>Ещё несколько лет назад для создания собственной музыки нужно было уметь играть на инструментах, работать в музыкальной программе или обращаться к композитору.</p><p>Сегодня первый музыкальный трек можно создать с помощью искусственного интеллекта.</p><p>Вы описываете словами, какую музыку хотите услышать, а нейросеть генерирует композицию: мелодию, аранжировку, инструменты, ритм, а при необходимости – вокал и текст песни.</p><p>Для этого необязательно знать ноты или разбираться в музыкальном продакшене.</p><p>Можно начать с простой идеи:</p><p className="font-semibold text-[#25135c]">«Спокойная инструментальная музыка для массажа, мягкое пианино, тёплые струнные, без вокала».</p><p>Через несколько минут у вас уже будут первые варианты.</p><p>Но хороший результат обычно появляется не с первой генерации. Поэтому разберём весь процесс последовательно – от идеи до готового музыкального трека.</p></div></header>
    <CreationFlowVisual />
    <section className={section} id="korotko"><h2 className={heading}>Коротко</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Чтобы создать музыку с помощью ИИ, нужно выбрать нейросеть для генерации музыки, описать желаемый результат, указать стиль и настроение, создать несколько вариантов, выбрать лучший и при необходимости доработать его.</p><p>Например, в Suno можно создать обычную песню с вокалом или включить инструментальный режим и получить музыку без слов. В расширенном режиме можно отдельно задавать текст песни, музыкальный стиль и дополнительные параметры.</p><p>Главное – начинать не с вопроса «какую кнопку нажать», а с вопроса:</p><p className="font-semibold text-[#25135c]">Какую музыку я хочу получить и для чего она будет использоваться?</p></div></section>
    <section className={section} id="shag-1"><h2 className={heading}>Шаг 1. Определите, какую музыку вы хотите создать</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Самая частая ошибка начинающего нейрокомпозитора – открыть генератор и написать что-нибудь вроде:</p><p className="font-semibold text-[#25135c]">«Создай красивую музыку».</p><p>Нейросеть действительно что-то создаст. Но результат будет случайным.</p><p>Гораздо лучше сначала определить назначение будущей композиции.</p><p>Например:</p><ul><li>музыка для сна;</li><li>музыка для массажа;</li><li>музыка для медитации;</li><li>спокойная музыка для работы;</li><li>фоновый джаз для кафе;</li><li>музыка для йоги;</li><li>атмосферная музыка для видео;</li><li>песня с вокалом;</li><li>инструментальная композиция.</li></ul><p>Это сразу даёт нейросети направление.</p><p>Сравните два запроса.</p><p><b>Слишком общий:</b></p><p>«Красивая спокойная музыка».</p><p><b>Более понятный:</b></p><p>«Спокойная инструментальная музыка для вечернего массажа. Мягкое пианино, тёплые струнные, лёгкий эмбиент, медленный темп, расслабляющая атмосфера, без вокала».</p><p>Во втором случае вероятность получить подходящий результат намного выше.</p></div></section>
    <section className={section} id="shag-2"><h2 className={heading}>Шаг 2. Выберите нейросеть для создания музыки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Сейчас существует много сервисов, которые умеют создавать музыку с помощью искусственного интеллекта.</p><p>Один из самых известных – Suno. В нём можно создать музыку по обычному текстовому описанию, использовать собственный текст песни или включить инструментальный режим.</p><p>Но Suno – не единственный вариант.</p><p>Поэтому отдельную статью мы сделаем позже:</p><p className="font-semibold text-[#25135c]">«В какой нейросети создать музыку: сервисы для начинающих».</p><p>А здесь важен сам принцип. Практически во всех современных генераторах путь похож:</p><p className="font-semibold text-[#25135c]">идея → описание → генерация → выбор варианта → доработка → готовая музыка.</p></div></section>
    <section className={section} id="shag-3"><h2 className={heading}>Шаг 3. Напишите хороший запрос для нейросети</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Запрос, который вы вводите в генератор музыки, часто называют промптом.</p><p>Не нужно пытаться написать сложный технический текст.</p><p>Лучше дать нейросети несколько понятных характеристик будущей музыки.</p><p>Хороший промпт обычно отвечает на вопросы:</p><p className="font-semibold text-[#25135c]">Что это за музыка? Какое настроение? Какие инструменты? Какой темп? Где она будет использоваться? Нужен ли вокал?</p><p>Например:</p><p>«Спокойная атмосферная музыка для SPA. Медленный темп, мягкое пианино, воздушные синтезаторы, лёгкие звуки природы, плавное развитие, без резких переходов, без вокала».</p><p>Или:</p><p>«Фоновый lounge jazz для дорогого ресторана вечером. Piano, upright bass, soft drums, warm saxophone, elegant relaxed atmosphere».</p><p>Не обязательно использовать английский язык. Многие современные сервисы понимают запросы на русском. Но иногда разные формулировки дают разные результаты, поэтому стоит экспериментировать.</p></div><PromptVisual /></section>
    <section className={section} id="shag-4"><h2 className={heading}>Шаг 4. Выберите – песня или музыка без слов</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>ИИ умеет создавать и песни с вокалом, и инструментальную музыку.</p><p>Если вам нужна песня, можно задать тему и позволить нейросети предложить текст либо использовать собственные слова.</p><p>Suno, например, позволяет вводить собственный текст песни в <a className={linkClass} href="https://help.suno.com/en/articles/2415873" target="_blank" rel="noopener noreferrer">Custom Mode</a>.</p><p>Если нужна музыка для сна, массажа, медитации, работы, SPA или йоги, чаще нужен инструментальный вариант.</p><p>В Suno для этого существует <a className={linkClass} href="https://help.suno.com/en/articles/3726721" target="_blank" rel="noopener noreferrer">инструментальный режим</a>.</p><p>Это важное разделение.</p><p>Запрос «создать песню с помощью ИИ» и запрос «создать фоновую музыку с помощью ИИ» отражают разные задачи. Поэтому этим темам мы позже посвятим отдельные статьи.</p></div></section>
    <section className={section} id="shag-5"><h2 className={heading}>Шаг 5. Создайте несколько вариантов</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Не стоит останавливаться на первой генерации.</p><p>ИИ-музыка во многом похожа на работу с фотографом: один кадр может оказаться обычным, а следующий – именно тем, что нужно.</p><p>Создайте несколько вариантов одной идеи.</p><p>Потом сравните:</p><ul><li>мелодию;</li><li>вступление;</li><li>развитие;</li><li>инструменты;</li><li>настроение;</li><li>качество вокала;</li><li>резкие переходы;</li><li>финал композиции.</li></ul><p>Если результат почти подходит, измените промпт совсем немного.</p><p>Например, было:</p><p className="font-semibold text-[#25135c]">«спокойная музыка для массажа»</p><p>Можно уточнить:</p><p className="font-semibold text-[#25135c]">«очень медленная музыка для массажа, без ударных, мягкое пианино, тёплый эмбиент, плавное развитие».</p><p>Так постепенно появляется собственное понимание того, какие слова дают нужный звук.</p></div><VariantsVisual /></section>
    <section className={section} id="shag-6"><h2 className={heading}>Шаг 6. Не пытайтесь сразу создать один час музыки</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Это особенно важно для тех, кто хочет создавать музыку для сна, массажа, SPA, йоги или работы.</p><p>Не обязательно заставлять нейросеть сделать одну композицию продолжительностью 30 или 60 минут.</p><p>Гораздо практичнее создать несколько хороших коротких композиций.</p><p>Например:</p><p className="font-semibold text-[#25135c]">10 треков примерно по 6 минут = около часа музыки.</p><p>Или:</p><p className="font-semibold text-[#25135c]">15 более коротких композиций = полноценная часовая музыкальная программа.</p><p>Так можно собрать:</p><p>Музыка для массажа – 60 минут</p><p>Музыка для SPA – 60 минут</p><p>Спокойная музыка для работы – 45 минут</p><p>Музыка для сна – 30 минут</p><p>Это особенно удобно для нейромузыки, потому что естественный формат генераторов – отдельные композиции, а уже затем из них можно собирать альбомы, программы и тематические плейлисты.</p></div><HourVisual /></section>
    <section className={section} id="shag-7"><h2 className={heading}>Шаг 7. Сохраните лучший результат и оформите его как музыкальный продукт</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Когда композиция готова, работа нейрокомпозитора на этом не заканчивается.</p><p>Музыке нужны:</p><ul><li>название;</li><li>обложка;</li><li>понятное описание;</li><li>назначение.</li></ul><p>Сравните:</p><p className="font-semibold text-[#25135c]">Moonlight Dreams</p><p>и</p><p className="font-semibold text-[#25135c]">Спокойная музыка для массажа</p><p>Первое название может быть красивым, но второе сразу объясняет слушателю, зачем ему эта композиция.</p><p>Это особенно важно, если вы рассчитываете, что музыку будут находить через поиск.</p></div></section>
    <AiMusicIntroCta />
    <section className={section} id="besplatno"><h2 className={heading}>Можно ли создать ИИ-музыку бесплатно</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Да, у некоторых музыкальных нейросетей есть бесплатные режимы.</p><p>Например, у Suno есть бесплатный режим. Но здесь важно разделять возможность <b>создать музыку бесплатно</b> и право <b>зарабатывать на этой музыке</b>.</p><p>Если вы просто экспериментируете – бесплатного режима может быть достаточно.</p><p>Согласно <a className={linkClass} href="https://help.suno.com/en/articles/9601601" target="_blank" rel="noopener noreferrer">актуальным правилам бесплатного плана Suno</a>, созданные на нём треки предназначены для личного некоммерческого использования и не могут монетизироваться.</p><p>Если планируете продавать треки, размещать их на стримингах или использовать в коммерческих проектах – перед созданием музыки обязательно изучите актуальные условия выбранного сервиса.</p></div></section>
    <section className={section} id="prodazha"><h2 className={heading}>Можно ли потом продавать музыку, созданную ИИ</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Во многих случаях – да, но всё зависит от условий конкретной нейросети и тарифа, на котором была создана композиция.</p><p>Важно различать три вещи:</p><p className="font-semibold text-[#25135c]">возможность скачать музыку, право использовать её коммерчески и авторско-правовую защиту.</p><p>Это не одно и то же.</p><p>Перед коммерческим использованием необходимо проверить актуальные условия конкретного сервиса, происхождение используемых материалов и правила площадки, где музыка будет продаваться или публиковаться. В <a className={linkClass} href="https://suno.com/terms-of-service" target="_blank" rel="noopener noreferrer">Terms Suno</a> указано, что условия использования и права на Output зависят от тарифа и соблюдения условий сервиса.</p><p>Подробнее про распространение:</p><p><Link href="/distribyutor-ii-muzyki" className={linkClass}>Дистрибьютор ИИ-музыки: где публиковать и продавать нейромузыку</Link></p><p>А про модель заработка внутри платформы:</p><p><Link href="/kak-zarabatyvat-na-ii-muzyke-v-audiolad" className={linkClass}>Как зарабатывать на своей ИИ-музыке в АудиоЛаде</Link></p></div></section>
    <section className={section} id="posle-pervogo-treka"><h2 className={heading}>Что делать после создания первого трека</h2><div className={`mt-5 ${articleBodyStackClass}`}><p>Не нужно сразу пытаться выпустить большой альбом.</p><p>Создайте одну композицию, которой вы действительно довольны.</p><p>Потом вторую.</p><p>Потом несколько произведений одной тематики.</p><p>Например, сначала можно собрать небольшую серию:</p><p className="font-semibold text-[#25135c]">музыка для массажа → музыка для SPA → музыка для сна → музыка для медитации → музыка для работы.</p><p>Через некоторое время это уже будет не набор случайных генераций, а собственный каталог.</p><p>И вот здесь ИИ из интересного инструмента начинает превращаться в средство производства музыкального контента.</p></div></section>
    <section className={section} id="faq"><h2 className={heading}>Частые вопросы</h2><ArticleFaqList items={KAK_SOZDAT_II_MUZYKU_FAQ} /></section>
  </article>;
}
