export {
  KAK_SOZDAT_MUZYKU_V_SUNO_BREADCRUMB_TITLE,
  KAK_SOZDAT_MUZYKU_V_SUNO_DATE_PUBLISHED,
  KAK_SOZDAT_MUZYKU_V_SUNO_FAQ,
  KAK_SOZDAT_MUZYKU_V_SUNO_PAGE_H1,
  KAK_SOZDAT_MUZYKU_V_SUNO_PATH,
  KAK_SOZDAT_MUZYKU_V_SUNO_SEO_DESCRIPTION,
  KAK_SOZDAT_MUZYKU_V_SUNO_SEO_TITLE,
  type KakSozdatMuzykuVSunoFaqItem,
} from "./content";
