-- Idempotent Wordstat seed: 60 approved jazz music-product search queries.
-- Source data checked on 2026-09-23 for the Wordstat period 22.08.2026–22.09.2026.
-- normalized_query is generated by public.set_seo_query_normalized(); conflict handling uses its unique constraint.
-- Existing real query_text, frequency, frequency_checked_at, and source are never overwritten.

BEGIN;

INSERT INTO public.seo_queries (
  query_text,
  frequency,
  frequency_checked_at,
  intent,
  recommended_format,
  audio_fit,
  analysis_status,
  source
)
VALUES
  ('джаз без слов', 1926, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('фоновый джаз', 1743, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для ресторана', 1740, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('мягкий джаз', 1584, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('вечерний джаз', 1381, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для кафе и ресторанов', 1214, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для отдыха', 971, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз лаунж', 824, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для работы', 795, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('романтический джаз', 578, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий джаз для кафе', 558, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний джаз за чашкой кофе', 496, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий джаз для ресторана', 450, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('кофейный джаз', 409, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('современный джаз фанк', 393, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('современный джаз рок', 298, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для сна', 296, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий фоновый джаз', 288, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз релакс саксофон', 239, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний веселый джаз', 173, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний позитивный джаз', 170, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний джаз босса нова', 162, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойный фоновый джаз', 156, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('фоновый джаз для кафе и ресторанов', 153, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойный джаз без слов', 145, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('современный русский джаз', 129, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('летний джаз для кафе', 128, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий джаз для отдыха', 126, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойный джаз саксофон', 122, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий утренний джаз', 121, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойный джаз в кафе', 106, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('французский утренний джаз', 105, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойный утренний джаз', 100, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('ночной джаз блюз', 98, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('мягкий утренний джаз', 97, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий джаз без слов', 96, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий расслабляющий джаз', 92, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('нежный утренний джаз', 92, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('фоновый джаз без слов', 89, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('осенний джаз саксофон', 85, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний джаз для настроения', 79, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий спокойный джаз', 70, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('инструментальный джаз релакс', 68, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий джаз пианино', 68, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('нуар джаз саксофон', 68, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('медленный уютный джаз', 65, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('ночной джаз саксофон', 65, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('современный джаз блюз', 65, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('бархатный саксофон джаз', 59, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('осенний джаз для кафе', 58, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('тихий спокойный джаз', 57, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('вечерний джаз саксофон', 56, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий осенний джаз', 56, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний осенний джаз', 56, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('легкий инструментальный джаз', 54, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('современный джаз вокал', 53, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('утренний джаз релакс', 53, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('веселый джаз без слов', 51, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз для учебы и отдыха', 51, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('джаз саксофон и кларнет', 51, DATE '2026-09-23', 'music', 'Музыка', 'high', 'analyzed', 'manual')
ON CONFLICT (normalized_query) DO UPDATE SET
  frequency = COALESCE(public.seo_queries.frequency, EXCLUDED.frequency),
  frequency_checked_at = COALESCE(
    public.seo_queries.frequency_checked_at,
    EXCLUDED.frequency_checked_at
  ),
  intent = COALESCE(public.seo_queries.intent, EXCLUDED.intent),
  recommended_format = COALESCE(
    public.seo_queries.recommended_format,
    EXCLUDED.recommended_format
  ),
  audio_fit = COALESCE(public.seo_queries.audio_fit, EXCLUDED.audio_fit);

COMMIT;
