-- Idempotent Wordstat calm-music seed, part 1/12 (100 approved queries).
-- Source checked on 2026-09-26; curated range 50-2000.
BEGIN;
INSERT INTO public.seo_queries (query_text, frequency, frequency_checked_at, intent, recommended_format, audio_fit, analysis_status, source)
VALUES
  ('спокойная музыка для снятия стресса', 1990, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('нежная спокойная музыка', 1974, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка без слов онлайн бесплатно', 1958, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка без слов слушать онлайн бесплатно', 1941, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать музыку бесплатно спокойную красивую', 1920, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка онлайн спокойная для души', 1897, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка спокойная мелодия', 1881, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка спокойная красивая без слов слушать', 1826, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная классическая музыка слушать', 1820, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для души слушать онлайн', 1769, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка природы', 1726, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для детей для рисования', 1689, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для детей в саду', 1681, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для детей в детском саду', 1665, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для медитации', 1639, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка для души очень спокойная', 1620, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для души очень красивая', 1561, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('красивая спокойная музыка для души бесплатно', 1435, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать музыку спокойную и красивую', 1435, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойную музыку для сна бесплатно', 1390, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для отдыха', 1382, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная русская музыка', 1310, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для уроков', 1300, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('очень спокойная музыка без слов', 1280, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать очень спокойную музыку', 1252, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка спокойная для души онлайн бесплатно', 1233, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для детей без слов', 1219, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('хорошая спокойная музыка для души', 1215, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка джаз', 1211, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для сна слушать бесплатно', 1191, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать спокойную музыку очень красивая музыка', 1189, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка спокойная для компьютера', 1187, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('очень красивая спокойная музыка без слов', 1176, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для релаксации', 1173, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для работы за компьютером', 1169, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать музыку онлайн бесплатно спокойную для души', 1140, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка без остановки слушать онлайн', 1139, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать музыку спокойную и красивую для души', 1135, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка для души очень спокойная слушать', 1132, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать спокойную музыку для души очень красивая', 1117, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для чтения', 1088, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('сборник спокойной музыки', 1080, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для сна онлайн', 1067, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка дождя', 1063, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('красивую спокойную нежную музыку', 1055, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная хорошая музыка для души бесплатно', 1053, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная грустная музыка', 1047, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для сна слушать онлайн', 1033, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для концентрации', 1030, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('хорошая спокойная музыка для души слушать', 1015, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для занятий', 1007, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка днем', 1006, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная зарубежная музыка', 1006, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная успокаивающая музыка', 977, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('радио спокойная музыка', 968, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка спокойная красивая без слов бесплатно', 944, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для души без остановки', 921, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная и очень нежная музыка', 902, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать спокойную музыку для сна детям', 900, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка в машину', 889, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать спокойную музыку для рисования', 883, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка море', 878, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('очень красивая нежная спокойная музыка', 876, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для детского сна', 876, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка без слов спокойная лучшая', 875, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка со словами', 872, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('мультик музыка спокойная', 871, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка онлайн красивая спокойная', 860, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка лето', 855, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('послушать спокойную музыку', 853, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная осенняя музыка', 847, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная красивая музыка без слов слушать бесплатно', 847, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('хорошая спокойная красивая музыка', 842, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка красивую спокойную слушать онлайн', 841, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('веселая спокойная музыка', 840, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная усыпляющая музыка', 821, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка на ночь', 819, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('медленная спокойная музыка', 806, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная усыпляющая музыка для сна', 805, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для сна слушать онлайн бесплатно', 797, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная классическая музыка слушать бесплатно', 776, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка тихая спокойная слушать', 771, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для вечера', 768, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для рисования детей слушать', 766, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('онлайн бесплатно спокойная красивая музыка', 762, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная электронная музыка', 761, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка подряд', 758, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать музыку онлайн бесплатно красивая спокойная', 756, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная тихая музыка без слов', 751, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('музыка для сна спокойная расслабляющая', 749, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная красивая музыка без остановки слушать', 744, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('слушать спокойную музыку для работы', 744, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная уютная музыка', 742, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('самая спокойная музыка', 740, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка слушать подряд', 739, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка для сна малышам лето', 737, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('хорошая спокойная музыка без слов слушать', 735, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная музыка фортепиано', 735, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная без слов качество музыки', 732, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual'),
  ('спокойная популярная музыка', 731, DATE '2026-09-26', 'music', 'Музыка', 'high', 'analyzed', 'manual')
ON CONFLICT (normalized_query) DO UPDATE SET
  frequency = COALESCE(public.seo_queries.frequency, EXCLUDED.frequency),
  frequency_checked_at = COALESCE(public.seo_queries.frequency_checked_at, EXCLUDED.frequency_checked_at),
  intent = COALESCE(public.seo_queries.intent, EXCLUDED.intent),
  recommended_format = COALESCE(public.seo_queries.recommended_format, EXCLUDED.recommended_format),
  audio_fit = COALESCE(public.seo_queries.audio_fit, EXCLUDED.audio_fit);
COMMIT;
